// === EXAMEN ===
function renderExamen(){const c=document.getElementById('app-content');if(currentState.exam.active){renderExamQuestion();return;}
const exams=MOCK_DATA.examens;const list=exams.map(ex=>'<div class="bg-white dark:bg-slate-800 rounded-2xl p-5 border shadow-sm kw-hover transition-all" style="border-color:var(--card-border)"><div class="flex items-center justify-between"><div><h3 class="text-lg font-bold text-slate-800 dark:text-white mb-1">'+ex.title+'</h3><p class="text-slate-400 text-sm">'+ex.description+'</p></div><button onclick="startExam(\''+ex.id+'\')" class="px-5 py-2 bg-brand-500 hover:bg-brand-600 text-white rounded-xl font-medium text-sm transition-colors shadow-sm">Démarrer</button></div></div>').join('');
c.innerHTML='<div class="max-w-3xl mx-auto"><h2 class="text-2xl font-bold text-slate-800 dark:text-white mb-2">Simulateur d\'Examen</h2><p class="text-slate-400 text-sm mb-6">Conditions réelles : chronomètre, pas de retour en arrière recommandé.</p><div class="space-y-4">'+list+'</div></div>';lucide.createIcons();}
function startExam(id){const ex=MOCK_DATA.examens.find(e=>e.id===id);currentState.exam={selectedExamId:id,active:true,timeRemaining:ex.duration,currentQuestionIndex:0,answers:{},timerInterval:null};currentState.exam.timerInterval=setInterval(()=>{currentState.exam.timeRemaining--;if(currentState.exam.timeRemaining<=0){clearInterval(currentState.exam.timerInterval);submitExam();}updateTimerDisplay();},1000);renderExamQuestion();updateStreak();}
function updateTimerDisplay(){const el=document.getElementById('exam-timer');if(el)el.textContent=formatTime(currentState.exam.timeRemaining);}
function renderExamQuestion(){const c=document.getElementById('app-content');const ex=MOCK_DATA.examens.find(e=>e.id===currentState.exam.selectedExamId);const q=ex.questions[currentState.exam.currentQuestionIndex];const total=ex.questions.length;const cur=currentState.exam.currentQuestionIndex;const sel=currentState.exam.answers[cur];
const opts=q.o.map((o,i)=>'<button onclick="selectAnswer('+cur+','+i+')" class="w-full text-left p-3.5 rounded-xl border transition-all text-sm '+(sel===i?'border-brand-500 bg-brand-50 dark:bg-brand-900/20 text-brand-600 ring-1 ring-brand-500':'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 hover:border-brand-300 cursor-pointer')+'"><span class="font-medium">'+o+'</span></button>').join('');
const dots=ex.questions.map((_,i)=>'<div class="w-2.5 h-2.5 rounded-full transition-colors '+(i===cur?'bg-brand-500 scale-125':currentState.exam.answers[i]!==undefined?'bg-brand-300':'bg-slate-200 dark:bg-slate-600')+'"></div>').join('');
c.innerHTML='<div class="max-w-2xl mx-auto"><div class="flex justify-between items-center mb-5"><h2 class="text-lg font-bold text-slate-800 dark:text-white">'+ex.title+'</h2><div class="flex items-center gap-2 text-brand-500 font-mono font-bold"><i data-lucide="clock" class="w-4 h-4"></i><span id="exam-timer">'+formatTime(currentState.exam.timeRemaining)+'</span></div></div><div class="bg-white dark:bg-slate-800 rounded-2xl p-6 border shadow-sm" style="border-color:var(--card-border)"><div class="flex justify-between items-center mb-5"><span class="text-sm font-medium text-brand-500 bg-brand-50 dark:bg-brand-900/30 px-3 py-1 rounded-md">Q'+(cur+1)+'/'+total+'</span></div><h3 class="text-lg font-semibold text-slate-800 dark:text-white mb-6">'+q.q+'</h3><div class="space-y-2.5">'+opts+'</div></div><div class="flex items-center justify-between mt-5"><button onclick="navigateExam(-1)" class="px-4 py-2 text-sm text-slate-400 hover:text-slate-700 dark:hover:text-white rounded-xl transition-colors '+(cur===0?'invisible':'')+'"><i data-lucide="arrow-left" class="w-4 h-4 inline mr-1"></i>Précédent</button><div class="flex gap-1.5 items-center">'+dots+'</div>'+(cur===total-1?'<button onclick="submitExam()" class="px-5 py-2 bg-brand-500 hover:bg-brand-600 text-white rounded-xl font-medium text-sm transition-colors">Terminer</button>':'<button onclick="navigateExam(1)" class="px-4 py-2 text-sm text-brand-500 hover:text-brand-700 rounded-xl transition-colors">Suivant<i data-lucide="arrow-right" class="w-4 h-4 inline ml-1"></i></button>')+'</div></div>';lucide.createIcons();}
function selectAnswer(qi,ai){currentState.exam.answers[qi]=ai;renderExamQuestion();}
function navigateExam(d){const ex=MOCK_DATA.examens.find(e=>e.id===currentState.exam.selectedExamId);const n=currentState.exam.currentQuestionIndex+d;if(n>=0&&n<ex.questions.length){currentState.exam.currentQuestionIndex=n;renderExamQuestion();}}
function submitExam(){clearInterval(currentState.exam.timerInterval);const ex=MOCK_DATA.examens.find(e=>e.id===currentState.exam.selectedExamId);const qs=ex.questions;let score=0;const timeSpent=ex.duration-currentState.exam.timeRemaining;
const results=qs.map((q,i)=>{const sel=currentState.exam.answers[i];const ok=sel===q.a;if(ok)score++;return '<div class="p-4 rounded-xl border mb-3 '+(ok?'border-green-200 bg-green-50/50 dark:bg-green-900/10 dark:border-green-900':'border-red-200 bg-red-50/50 dark:bg-red-900/10 dark:border-red-900')+'" style="border-color:var(--card-border)"><div class="flex items-start gap-3"><i data-lucide="'+(ok?'check-circle':'x-circle')+'" class="w-5 h-5 mt-0.5 '+(ok?'text-green-500':'text-red-500')+'"></i><div class="flex-1"><p class="font-medium text-sm text-slate-800 dark:text-white mb-1">Q'+(i+1)+'. '+q.q+'</p><p class="text-xs text-slate-500 mb-1">Votre réponse : <span class="'+(ok?'text-green-600':'text-red-600')+' font-medium">'+(sel!==undefined?q.o[sel]:'Non répondu')+'</span></p>'+(ok?'':'<p class="text-xs text-green-600 dark:text-green-400">✓ '+q.o[q.a]+'</p>')+'<p class="text-xs text-slate-400 mt-1">'+q.e+'</p></div></div></div>';}).join('');
const pct=Math.round(score/qs.length*100);const c=document.getElementById('app-content');
c.innerHTML='<div class="max-w-3xl mx-auto"><div class="text-center mb-8 bg-white dark:bg-slate-800 rounded-2xl p-8 border shadow-sm" style="border-color:var(--card-border)"><div class="relative w-28 h-28 mx-auto mb-4"><svg class="w-28 h-28 -rotate-90" viewBox="0 0 100 100"><circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" stroke-width="8" class="text-slate-100 dark:text-slate-700"></circle><circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" stroke-width="8" stroke-dasharray="283" stroke-dashoffset="'+(283-283*pct/100)+'" class="'+(pct>=50?'text-green-500':'text-red-500')+' transition-all duration-1000"></circle></svg><div class="absolute inset-0 flex flex-col items-center justify-center"><span class="text-3xl font-bold '+(pct>=50?'text-green-500':'text-red-500')+'">'+score+'</span><span class="text-slate-400 text-sm font-medium">/'+qs.length+'</span></div></div><div class="flex gap-6 justify-center text-slate-500 dark:text-slate-400 text-sm"><div class="flex flex-col items-center"><i data-lucide="clock" class="w-4 h-4 mb-1"></i><span>'+formatTime(timeSpent)+'</span></div><div class="flex flex-col items-center"><i data-lucide="target" class="w-4 h-4 mb-1"></i><span>'+pct+'%</span></div></div><button onclick="currentState.exam.selectedExamId=null;currentState.exam.active=false;navigate(\'examen\')" class="mt-6 px-6 py-2 bg-slate-100 dark:bg-slate-700 text-slate-800 dark:text-white rounded-xl font-medium text-sm hover:bg-slate-200 transition-colors">Retour</button></div><h3 class="text-lg font-bold text-slate-800 dark:text-white mb-4">Correction</h3>'+results+'</div>';lucide.createIcons();
if(pct>=75){triggerConfetti();showToast('Bravo ! '+pct+'% de réussite !');}else showToast('Score : '+pct+'%');
if(!MOCK_DATA.user.examsCompleted)MOCK_DATA.user.examsCompleted=[];if(pct>=50&&!MOCK_DATA.user.examsCompleted.includes(ex.id)){MOCK_DATA.user.examsCompleted.push(ex.id);MOCK_DATA.user.progress=Math.min(100,MOCK_DATA.user.progress+15);saveProgress();}
if(!MOCK_DATA.user.statsHistory)MOCK_DATA.user.statsHistory=[];MOCK_DATA.user.statsHistory.push({date:new Date().toLocaleDateString('fr-FR'),label:ex.title.substring(0,20),score:pct});saveProgress();
currentState.exam.active=false;currentState.exam.timeRemaining=0;currentState.exam.answers={};}

// === POMODORO ===
function renderPomodoro(){const c=document.getElementById('app-content');const isKw=document.documentElement.getAttribute('data-theme')==='kawaii';const isWork=pomodoroState.mode==='work';
c.innerHTML='<div class="max-w-md mx-auto text-center"><h2 class="text-2xl font-bold text-slate-800 dark:text-white mb-2">Pomodoro Timer '+(isKw?'🍅':'')+'</h2><p class="text-slate-400 text-sm mb-8">25 min de travail, 5 min de pause.</p><div class="bg-white dark:bg-slate-800 rounded-3xl p-10 border shadow-lg mx-auto" style="border-color:var(--card-border)"><div class="mb-4"><span class="text-xs font-bold uppercase tracking-widest '+(isWork?'text-brand-500':'text-green-500')+'">'+(isWork?'Travail':'Pause')+'</span></div><div class="text-7xl font-extrabold text-slate-800 dark:text-white mb-8 font-mono '+(pomodoroState.running?'pomo-pulse':'')+'">'+formatTime(pomodoroState.timeLeft)+'</div><div class="flex justify-center gap-4"><button onclick="togglePomodoro()" class="px-8 py-3 '+(pomodoroState.running?'bg-red-500 hover:bg-red-600':'bg-brand-500 hover:bg-brand-600')+' text-white rounded-xl font-bold transition-colors shadow-md"><i data-lucide="'+(pomodoroState.running?'pause':'play')+'" class="w-5 h-5 inline mr-2"></i>'+(pomodoroState.running?'Pause':'Démarrer')+'</button><button onclick="resetPomodoro()" class="px-6 py-3 bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 rounded-xl font-medium hover:bg-slate-200 transition-colors"><i data-lucide="rotate-ccw" class="w-4 h-4 inline mr-1"></i>Reset</button></div></div><div class="mt-8 grid grid-cols-2 gap-4"><div class="bg-white dark:bg-slate-800 rounded-xl p-4 border text-center" style="border-color:var(--card-border)"><p class="text-2xl font-bold text-brand-500">25<span class="text-sm text-slate-400 font-normal"> min</span></p><p class="text-xs text-slate-400 mt-1">Session de travail</p></div><div class="bg-white dark:bg-slate-800 rounded-xl p-4 border text-center" style="border-color:var(--card-border)"><p class="text-2xl font-bold text-green-500">5<span class="text-sm text-slate-400 font-normal"> min</span></p><p class="text-xs text-slate-400 mt-1">Pause</p></div></div></div>';lucide.createIcons();}
function togglePomodoro(){if(pomodoroState.running){clearInterval(pomodoroState.interval);pomodoroState.running=false;}else{pomodoroState.running=true;pomodoroState.interval=setInterval(()=>{pomodoroState.timeLeft--;if(pomodoroState.timeLeft<=0){clearInterval(pomodoroState.interval);pomodoroState.running=false;if(pomodoroState.mode==='work'){pomodoroState.mode='break';pomodoroState.timeLeft=5*60;triggerConfetti();showToast('Pause ! Reposez-vous 5 min 🎉');}else{pomodoroState.mode='work';pomodoroState.timeLeft=25*60;showToast('C\'est reparti ! 💪');}}if(currentState.page==='pomodoro')renderPomodoro();},1000);}renderPomodoro();}
function resetPomodoro(){clearInterval(pomodoroState.interval);pomodoroState={running:false,timeLeft:25*60,mode:'work',interval:null};renderPomodoro();}

// === STATS ===
function renderStats(){const c=document.getElementById('app-content');const{user}=MOCK_DATA;const history=user.statsHistory||[];const isKw=document.documentElement.getAttribute('data-theme')==='kawaii';
let barsHtml='<p class="text-slate-400 text-sm text-center py-8">Passez des examens pour voir vos statistiques ici.</p>';
if(history.length>0){const bars=history.slice(-10).map(h=>{const color=h.score>=75?'bg-green-500':h.score>=50?'bg-amber-500':'bg-red-500';return '<div class="flex items-end gap-1 flex-1"><div class="w-full flex flex-col items-center"><div class="text-xs font-bold text-slate-600 dark:text-slate-300 mb-1">'+h.score+'%</div><div class="w-full '+color+' rounded-t-lg transition-all" style="height:'+Math.max(h.score*1.5,10)+'px"></div><div class="text-[10px] text-slate-400 mt-1 truncate w-full text-center">'+h.label+'</div></div></div>';}).join('');
barsHtml='<div class="flex items-end gap-2 h-52 px-4">'+bars+'</div>';}
const totalQ=(user.quizzesCompletedIds||[]).length;const totalE=(user.examsCompleted||[]).length;
c.innerHTML='<div class="max-w-3xl mx-auto"><h2 class="text-2xl font-bold text-slate-800 dark:text-white mb-2">Statistiques '+(isKw?'📊':'')+'</h2><p class="text-slate-400 text-sm mb-6">Suivez votre progression au fil du temps.</p><div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8"><div class="bg-white dark:bg-slate-800 rounded-2xl p-5 border text-center" style="border-color:var(--card-border)"><p class="text-3xl font-extrabold text-brand-500">'+totalQ+'</p><p class="text-sm text-slate-400 mt-1">Quiz complétés</p></div><div class="bg-white dark:bg-slate-800 rounded-2xl p-5 border text-center" style="border-color:var(--card-border)"><p class="text-3xl font-extrabold text-green-500">'+totalE+'</p><p class="text-sm text-slate-400 mt-1">Examens réussis</p></div><div class="bg-white dark:bg-slate-800 rounded-2xl p-5 border text-center" style="border-color:var(--card-border)"><p class="text-3xl font-extrabold text-amber-500">'+(user.streak||0)+'</p><p class="text-sm text-slate-400 mt-1">Jours de suite 🔥</p></div></div><div class="bg-white dark:bg-slate-800 rounded-2xl p-6 border" style="border-color:var(--card-border)"><h3 class="text-lg font-bold text-slate-800 dark:text-white mb-4">Historique des scores</h3>'+barsHtml+'</div></div>';lucide.createIcons();}

// === INIT ===
navigate('dashboard');
