const EXAM_DATA = [
  {id:"ep1",title:"Organisation et tâches (Sujet A)",duration:15*60,description:"15 min - 15 questions",questions:[
    {q:"Chaque niveau descendant de la WBS doit :",o:["Regrouper les livrables du précédent","Être moins précis","Apporter plus de détails","Être assigné à un département"],a:2,e:"Affinement du détail."},
    {q:"Le composant le plus petit de la WBS s'appelle :",o:["Le Work Package","La phase de clôture","La tâche critique","Le jalon"],a:0,e:"Unité de base pour l'estimation."},
    {q:"La Règle des 100% exige que la WBS :",o:["Couvre 100% du budget","Soit validée par 100% de l'équipe","Couvre la totalité du périmètre","Contienne 100 paquets"],a:2,e:"Tout le travail y figure."},
    {q:"Lequel n'a PAS sa place dans une WBS logiciel ?",o:["Manuel utilisateur","Phase de test","Développeur Senior (Jean)","Code source"],a:2,e:"Jean est dans l'OBS."},
    {q:"L'OBS permet de définir :",o:["La chronologie","Qui est responsable de quoi","Le budget","L'analyse des risques"],a:1,e:"Organisation des responsabilités."},
    {q:"Qui se trouve souvent au sommet de l'OBS ?",o:["Le client","Le chef de projet","Le dev le plus expérimenté","Le fournisseur"],a:1,e:"Le chef de projet dirige."},
    {q:"Quel outil est généré par le croisement WBS × OBS ?",o:["PERT","Matrice RACI","Gantt","Registre des risques"],a:1,e:"WBS(Quoi) × OBS(Qui) = RACI."},
    {q:"'Couler la fondation' est :",o:["Une phase","Une ressource","Un Work Package","Un risque"],a:2,e:"Action de bas niveau."},
    {q:"La séquence temporelle est-elle indiquée dans la WBS ?",o:["Oui, de haut en bas","Oui, de gauche à droite","Non, la WBS définit seulement le périmètre","Uniquement pour les jalons"],a:2,e:"La WBS n'est pas un planning."},
    {q:"L'OBS peut inclure :",o:["Les coûts matériels","Des départements, équipes ou personnes","Toujours 3 niveaux","Le cahier des charges"],a:1,e:"Flexible selon l'organisation."},
    {q:"'Lot de travail' est synonyme de :",o:["Work Package","Organigramme fonctionnel","Jalon de projet","Livrable principal"],a:0,e:"Work Package = lot de travail."},
    {q:"L'identification des départements relève de :",o:["La WBS","La matrice des risques","L'OBS","Le PERT"],a:2,e:"Organisation Breakdown Structure."},
    {q:"Si une tâche n'est pas dans la WBS :",o:["Elle est externalisée","Elle est hors périmètre","Elle est dans l'OBS","Elle est implicite"],a:1,e:"Règle des 100%."},
    {q:"Le budget se construit à partir de :",o:["L'OBS seule","Avant la WBS","Les Work Packages (bottom-up)","La clôture"],a:2,e:"Estimation ascendante."},
    {q:"La décomposition s'arrête quand :",o:["Plus d'idées","On atteint un WP gérable","100 tâches atteintes","Le Gantt est terminé"],a:1,e:"Work Package = niveau optimal."}
  ]},
  {id:"ep2",title:"Organisation et tâches (Sujet B)",duration:15*60,description:"15 min - 15 questions",questions:[
    {q:"Que signifie WBS ?",o:["Work Breakdown Structure","Wide Business System","Workflow Basic System","Work Base Solution"],a:0,e:"Work Breakdown Structure."},
    {q:"Que signifie OBS ?",o:["Objective Breakdown Structure","Organization Breakdown Structure","Operational Base System","Organizational Business Solution"],a:1,e:"Organization Breakdown Structure."},
    {q:"La Règle des 100% repose sur :",o:["100% de l'équipe valide la WBS","Budget 100% défini","La WBS capture l'intégralité du travail","Chaque tâche achevée à 100% avant la suivante"],a:2,e:"Tout le travail inclus."},
    {q:"Lequel relève du 'Qui' ?",o:["WBS","Gantt","OBS","PERT"],a:2,e:"L'OBS organise les personnes."},
    {q:"Lequel relève du 'Quoi' ?",o:["WBS","OBS","RACI","Matrice des rôles"],a:0,e:"La WBS liste les livrables."},
    {q:"Le croisement WBS × OBS donne :",o:["Le cahier des charges","La matrice de responsabilités","Le Gantt","L'analyse fonctionnelle"],a:1,e:"La matrice RACI."},
    {q:"Peut-on mettre des durées dans la WBS ?",o:["Oui, c'est son rôle","Non, la WBS définit le périmètre","Oui, pour les WP","Non, dans l'OBS"],a:1,e:"Pas un planning."},
    {q:"'Installer les serveurs de production' est :",o:["Un élément OBS","Un élément WBS","Un élément RACI","Une responsabilité DBA"],a:1,e:"C'est une tâche/livrable."},
    {q:"'Équipe Développement Backend' est :",o:["Un élément WBS","Un élément OBS","Un lot de travail","Une phase de déploiement"],a:1,e:"Unité organisationnelle."},
    {q:"Pourquoi la WBS est 'hiérarchique' ?",o:["Montre le chef","Subdivisée du général au détaillé","Classe par chronologie","Priorités budgétaires"],a:1,e:"Décomposition en arbre."},
    {q:"Phase typique de premier niveau WBS logiciel ?",o:["OBS","RACI","Déploiement","Équipe Marketing"],a:2,e:"Phase clé du logiciel."},
    {q:"Le rôle d'une WBS est de :",o:["Rendre le travail compréhensible et gérable","Lister les employés","Vérifier la rentabilité","Concevoir le MCD"],a:0,e:"Faciliter la gestion."},
    {q:"Un Work Package doit pouvoir être :",o:["Confié à l'OBS","Omis si temps manque","Estimé en coût et charge de façon fiable","Sous-traité sans supervision"],a:2,e:"Base de l'estimation."},
    {q:"L'OBS se présente comme :",o:["Un tableau financier","Un organigramme classique","Un diagramme circulaire","Un planning"],a:1,e:"Arbre de management."},
    {q:"Erreur fatale dans la WBS ?",o:["Inclure les réunions","Oublier des livrables nécessaires","Plus de 3 niveaux","Utiliser des verbes"],a:1,e:"Violation de la règle des 100%."}
  ]},
  {id:"ep3",title:"S.I. et SGBD (Variante Inédite)",duration:30*60,description:"30 min - 22 questions",questions:[
    {q:"Objectif d'une architecture client-serveur ?",o:["Un seul utilisateur","Plusieurs clients accèdent à des services partagés","Stockage local uniquement","Gestion sans fil"],a:1,e:"Centralisation."},
    {q:"Fonctions d'un serveur ?",o:["Gérer l'affichage client","Fournir des ressources centralisées","Sécurité uniquement","Communication sans fil"],a:1,e:"Ressources centralisées."},
    {q:"Qu'est-ce qu'un LAN ?",o:["Réseau reliant des serveurs distants","Réseau local en zone restreinte","Réseau global","Réseau filaire uniquement"],a:1,e:"Local Area Network."},
    {q:"Fonction principale d'un VPN ?",o:["Gérer les permissions","Accélérer Internet","Créer un tunnel sécurisé","Filtrer les contenus"],a:2,e:"Virtual Private Network."},
    {q:"Rôle d'un pare-feu ?",o:["Stockage","Filtrer les paquets entrants/sortants","Accélérer le réseau","Gérer l'accès Internet"],a:1,e:"Sécurité réseau."},
    {q:"Fonction d'un routeur ?",o:["Attribuer des IP","Diriger les paquets vers leur destination","Gérer la communication filaire","Filtrer le trafic"],a:1,e:"Routage."},
    {q:"Une adresse IP est :",o:["Un identifiant numérique d'un appareil","Un identifiant physique","Une clé d'authentification","Un protocole"],a:0,e:"Identifiant réseau logique."},
    {q:"Objectif de la virtualisation ?",o:["Augmenter le stockage","Plusieurs VM sur un même serveur physique","Sécuriser le matériel","Réduire la latence"],a:1,e:"Optimisation du matériel."},
    {q:"Avantage du cloud public ?",o:["Plus sécurisé","Plus de contrôle","Gestion simplifiée sans infrastructure interne","Pas besoin d'internet"],a:2,e:"Externalisation."},
    {q:"Un ERP désigne :",o:["Un logiciel de sécurité","Un logiciel de gestion intégré","Un SGBD","Un logiciel réseau"],a:1,e:"Enterprise Resource Planning."},
    {q:"SGBD signifie :",o:["Système de Gestion de Bases de Données","Serveur de Gestion de BD","Système Général de BD","Service Global de BD"],a:0,e:"SGBD."},
    {q:"Une BDD relationnelle :",o:["Stocke des fichiers Excel","Organise les données en tables interconnectées","Stocke du texte","Utilise JSON"],a:1,e:"Modèle relationnel."},
    {q:"Une ligne de table = :",o:["Colonne","Tuple","Champ","Vue"],a:1,e:"Enregistrement."},
    {q:"La clé primaire sert à :",o:["Identifier chaque champ","Faire des calculs","Identifier chaque enregistrement de façon unique","Lier deux BDD"],a:2,e:"Unicité de la ligne."},
    {q:"Lien entre deux tables ?",o:["Clé étrangère","Index","Clé primaire","Trigger"],a:0,e:"Clé étrangère."},
    {q:"Dépendance fonctionnelle :",o:["Intégrité des données","La valeur d'un attribut dépend d'un autre","Optimisation des requêtes","Relation entre tables"],a:1,e:"A détermine B."},
    {q:"Le schéma d'une BDD :",o:["Le fichier de données","Le processus de sauvegarde","La structure des tables et contraintes","La clé primaire"],a:2,e:"Structure globale."},
    {q:"Association binaire en E/A :",o:["Lien clé primaire/étrangère","Relation sémantique entre deux entités","Comparaison de valeurs","Table à deux attributs"],a:1,e:"Relation entre deux objets."},
    {q:"Objectif de la normalisation :",o:["Fusionner les tables","Minimiser la redondance et éviter les anomalies","Garantir l'unicité des clés","Ajouter des données"],a:1,e:"Intégrité."},
    {q:"Anomalie si on ne respecte pas la 2FN ?",o:["Perte de données","Redondance dépendant d'une partie de la clé composée","Table illisible","Clés étrangères disparaissent"],a:1,e:"Dépendance partielle."},
    {q:"IaaS vs PaaS vs SaaS :",o:["IaaS=matériel, PaaS=plateforme dev, SaaS=logiciel final","Trois marques de serveurs","IaaS=Internet, PaaS=Password, SaaS=System","Aucune différence"],a:0,e:"3 niveaux de service cloud."},
    {q:"Fonction principale du DBA ?",o:["Configurer les routeurs","Assurer intégrité, performance et sauvegarde des BDD","Coder l'interface graphique","Créer la matrice RACI"],a:1,e:"Administrateur BDD."}
  ]},
  {id:"ep4",title:"Langage SQL (Variante Inédite)",duration:30*60,description:"30 min - 10 questions",questions:[
    {q:"Syntaxe correcte pour supprimer une ligne ?",o:["DROP ROW FROM t WHERE id=1","DELETE FROM t WHERE id=1","REMOVE id=1 FROM t","TRUNCATE t WHERE id=1"],a:1,e:"DELETE FROM."},
    {q:"Prix max par catégorie ?",o:["SELECT cat, MAX(prix) FROM p","SELECT cat, MAX(prix) FROM p GROUP BY cat","SELECT cat, MAX(prix) FROM p GROUP BY prix","SELECT MAX(prix) FROM p GROUP BY cat"],a:1,e:"GROUP BY categorie."},
    {q:"CREATE TABLE top AS SELECT ... WHERE price > (SELECT AVG(price) ...) :",o:["CREATE TABLE top AS SELECT ... WHERE price > AVG(price)","CREATE TABLE top SELECT ...","CREATE TABLE top AS SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products)","CREATE TABLE top (SELECT ...)"],a:2,e:"CREATE TABLE ... AS SELECT."},
    {q:"Ajouter une colonne :",o:["ALTER TABLE t ADD COLUMN c type","ALTER TABLE t MODIFY COLUMN c type","UPDATE TABLE t ADD COLUMN c","ALTER TABLE t CREATE COLUMN c"],a:0,e:"ALTER TABLE ... ADD COLUMN."},
    {q:"Éliminer les doublons dans le résultat :",o:["UNIQUE","DISTINCT","NO_REPEAT","LIMIT"],a:1,e:"SELECT DISTINCT."},
    {q:"LEFT JOIN + WHERE t2.col IS NULL retourne :",o:["Correspondances parfaites","Lignes de gauche sans correspondance à droite","Toutes les lignes des deux tables","Zéro résultat"],a:1,e:"Anti-jointure gauche."},
    {q:"COUNT(DISTINCT e.id) calcule :",o:["Nombre total de notes","Nombre d'étudiants uniques","Valeur max de l'ID","Nombre ayant validé"],a:1,e:"DISTINCT avant comptage."},
    {q:"NATURAL JOIN se base sur :",o:["L'ordre alphabétique","Les colonnes du même nom","Les valeurs NULL","Les clés auto-incrémentées"],a:1,e:"Jointure naturelle."},
    {q:"DELETE FROM Livres WHERE id NOT IN (SELECT DISTINCT id FROM Ventes) :",o:["Supprime les livres vendus","Supprime tout","Supprime les livres jamais vendus","Erreur SQL"],a:2,e:"Suppression des invendus."},
    {q:"Le DELIMITER $$ sert à :",o:["Déclarer les variables","Empêcher le SGBD de s'arrêter au premier ;","Définir le type de retour","Crypter la fonction"],a:1,e:"Changer le délimiteur standard."}
  ]}
];
